"""
Pydantic data models shared across the reactive pipeline.

Defines contracts between: Planner → Tools → Validation → LLM Agent.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------
class IntentType(str, Enum):
    """User query intent categories."""

    STATUS_QUERY = "status_query"          # Current ECG status query.
    ANOMALY_EXPLAIN = "anomaly_explain"    # Explanation of detected anomalies.
    ADVICE_REQUEST = "advice_request"      # Guidance or next-step request.
    HISTORY_COMPARE = "history_compare"    # Comparison against prior records.
    KNOWLEDGE_QA = "knowledge_qa"          # General medical knowledge question.
    RECORD_LIST = "record_list"            # Available ECG records listing.
    GENERAL_CHAT = "general_chat"            # Non-ECG conversation (no tools needed).


class RiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# ---------------------------------------------------------------------------
# Plan & Steps
# ---------------------------------------------------------------------------
class PlanStep(BaseModel):
    """A single step in the execution plan produced by the Planner."""

    step_id: int = Field(description="Step sequence number starting from 1")
    tool_name: str = Field(description="Name of the tool to invoke")
    tool_args: dict[str, Any] = Field(
        default_factory=dict,
        description="Arguments to pass to the tool",
    )
    description: str = Field(description="Human-readable description of this step")


class Plan(BaseModel):
    """Execution plan generated by the Planner."""

    intent: IntentType
    reasoning: str = Field(description="Planner's reasoning for this plan")
    steps: list[PlanStep] = Field(default_factory=list)
    original_query: str = ""


# ---------------------------------------------------------------------------
# Tool Results
# ---------------------------------------------------------------------------
class ToolResult(BaseModel):
    """Result returned by a single tool invocation."""

    step_id: int
    tool_name: str
    success: bool = True
    data: dict[str, Any] = Field(default_factory=dict)
    error: str = ""


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
class IssueSeverity(str, Enum):
    """Severity level of a validation issue."""

    CRITICAL = "critical"   # blocks answer generation, triggers replan
    WARNING = "warning"     # logged and passed to LLM context, does NOT trigger replan


class IssueType(str, Enum):
    """Category of validation issue."""

    MISSING_RESULT = "missing_result"              # planned step has no result
    TOOL_FAILURE = "tool_failure"                  # tool returned success=False
    MISSING_FIELD = "missing_field"                # required output field is empty
    CONSISTENCY_CONFLICT = "consistency_conflict"  # cross-tool contradiction detected


class ValidationIssue(BaseModel):
    """A single structured validation issue."""

    step_id: int | None = None
    tool_name: str = ""
    issue_type: IssueType
    severity: IssueSeverity
    message: str


class ValidationResult(BaseModel):
    """Output of the Validation Gate."""

    passed: bool
    issues: list[ValidationIssue] = Field(default_factory=list)
    coverage: float = Field(
        default=1.0,
        description="Fraction of required data successfully collected (0-1)",
    )

    @model_validator(mode="before")
    @classmethod
    def _coerce_legacy_issue_strings(cls, data: Any) -> Any:
        """Accept legacy list[str] issue payloads for direct construction."""
        if not isinstance(data, dict):
            return data

        raw_issues = data.get("issues")
        if not isinstance(raw_issues, list) or not raw_issues or not all(
            isinstance(issue, str) for issue in raw_issues
        ):
            return data

        severity = IssueSeverity.WARNING if data.get("passed", True) else IssueSeverity.CRITICAL
        data = dict(data)
        data["issues"] = [
            {
                "step_id": None,
                "tool_name": "",
                "issue_type": IssueType.TOOL_FAILURE,
                "severity": severity,
                "message": issue,
            }
            for issue in raw_issues
        ]
        return data

    @property
    def issue_messages(self) -> list[str]:
        """Backward-compatible: return issues as plain strings."""
        return [issue.message for issue in self.issues]

    @property
    def has_critical(self) -> bool:
        """Return True if any issue is CRITICAL severity."""
        return any(issue.severity == IssueSeverity.CRITICAL for issue in self.issues)

    @property
    def warnings(self) -> list[ValidationIssue]:
        """Return only WARNING-level issues."""
        return [issue for issue in self.issues if issue.severity == IssueSeverity.WARNING]

    @property
    def critical_issues(self) -> list[ValidationIssue]:
        """Return only CRITICAL-level issues."""
        return [issue for issue in self.issues if issue.severity == IssueSeverity.CRITICAL]


# ---------------------------------------------------------------------------
# Final Response
# ---------------------------------------------------------------------------
class AgentResponse(BaseModel):
    """Final response returned to the user."""

    answer: str
    risk_level: RiskLevel | None = None
    context_used: dict[str, Any] = Field(default_factory=dict)
    plan_history: list[Plan] = Field(default_factory=list)
    retry_count: int = 0
